name: cloudrun-deploy
on:
  pull_request:
    types: closed
    branches:
      - main
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    services:
      ports:
        - 3000:3000
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker


  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
    # Build the Docker image
    - name: Build
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}
        gcloud config set run/region us-central1

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    # Deploy the Docker image to the GKE cluster
    - name: Deploy to cloudrun
      id: deploy
      run: |
        gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} \
        --platform managed \
        --allow-unauthenticated \
        --memory 512M

  url:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    # Show url output
    - name: Show URL-Output
      run: echo ${{ steps.deploy.outputs.url }}
